"""add agent_runs, agent_steps, tool_calls, and approvals tables

Revision ID: 020ff21e491c
Revises: ceb2f38c32cb
Create Date: 2026-08-13 14:44:57.173503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '020ff21e491c'
down_revision: Union[str, None] = 'ceb2f38c32cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'AWAITING_APPROVAL', 'COMPLETED', 'FAILED', 'REJECTED', name='agentrunstatus'), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('max_runtime_seconds', sa.Integer(), nullable=False),
    sa.Column('max_tool_calls', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_organization_id'), 'agent_runs', ['organization_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='toolrisklevel'), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'AWAITING_APPROVAL', 'EXECUTED', 'FAILED', 'REJECTED', name='toolcallstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_agent_run_id'), 'tool_calls', ['agent_run_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PLANNING', 'TOOL_SELECTION', 'TOOL_EXECUTION', 'OBSERVATION', 'VERIFICATION', name='agentstepstate'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('raw_action_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_call_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_steps_agent_run_id'), 'agent_steps', ['agent_run_id'], unique=False)
    op.create_table('approvals',
    sa.Column('tool_call_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvaldecision'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_call_id')
    )
    # NOTE: autogenerate also proposed dropping ix_document_chunks_content_tsv_gin
    # and ix_document_chunks_embedding_hnsw here — both are real indexes (raw SQL)
    # not represented in SQLAlchemy's index metadata, so autogenerate incorrectly
    # saw them as extraneous. Same false positive as every migration since Phase 6;
    # removed by hand.
    #
    # agent_document_overview (ADR-012, decision 3): the ONLY table/view the
    # run_safe_sql tool is allowed to query. Deliberately excludes extracted_text
    # (could be large/sensitive) and never joins to users/refresh_tokens/any auth
    # table, so even a successful query cannot leak credentials or full document
    # bodies — a real security boundary, not just an access-control label.
    op.execute("""
        CREATE VIEW agent_document_overview AS
        SELECT
            d.id,
            d.organization_id,
            d.original_filename AS filename,
            d.status,
            d.size_bytes,
            d.created_at,
            c.name AS collection_name
        FROM documents d
        LEFT JOIN collections c ON c.id = d.collection_id
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS agent_document_overview")
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agent_steps_agent_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_tool_calls_agent_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_agent_runs_organization_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
