"""add full-text search tsvector column to document_chunks

Revision ID: d661b5f5c3ea
Revises: eb258bdbb9b1
Create Date: 2026-08-11 19:21:01.424555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd661b5f5c3ea'
down_revision: Union[str, None] = 'eb258bdbb9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False))
    # NOTE: autogenerate also proposed dropping ix_document_chunks_embedding_hnsw
    # here — that index is real (created via raw SQL in the previous migration,
    # see eb258bdbb9b1) but isn't represented in SQLAlchemy's index metadata,
    # so the autogenerate diff incorrectly saw it as extraneous. Removed that
    # line by hand; dropping it would have silently killed vector search
    # performance. Always read autogenerated output before trusting it.
    # ### end Alembic commands ###
    op.execute(
        "CREATE INDEX ix_document_chunks_content_tsv_gin ON document_chunks "
        "USING gin (content_tsv)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_content_tsv_gin")
    op.drop_column('document_chunks', 'content_tsv')
    # ### end Alembic commands ###
